// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Collection struct {
	ID        int64
	Name      string
	Userid    pgtype.Int8
	Color     string
	Createdat pgtype.Date
}

type Task struct {
	ID           int64
	Content      string
	Userid       pgtype.Int8
	Done         bool
	Expiresat    pgtype.Date
	Createdat    pgtype.Date
	Collectionid pgtype.Int8
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Email     string
	CreatedAt pgtype.Date
	UpdatedAt pgtype.Date
}
