// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
)

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections
WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, name, userid, color, createdat FROM collections
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCollection(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Userid,
		&i.Color,
		&i.Createdat,
	)
	return i, err
}
